export const VALUE_CHANGED = 'TEMPERATURE/VALUE_CHANGED';
export const LOW_LEVEL = 'TEMPERATURE/LOW_LEVEL';
export const HIGH_LEVEL = 'TEMPERATURE/HIGH_LEVEL';
export const NORMAL_LEVEL = 'TEMPERATURE/NORMAL_LEVEL';

